# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monthlyinterface.Creation'),
        ),
    ]
