# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0002_auto_20160104_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monthlyinterface.Creation'),
        ),
    ]
