# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0004_creation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=200)),
                ('desired_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthlyinterface.Desired_Format')),
            ],
        ),
        migrations.AddField(
            model_name='creation',
            name='filePath',
            field=models.CharField(default='fixMe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creation',
            name='materials',
            field=models.ManyToManyField(to='monthlyinterface.Material'),
        ),
    ]
