# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0006_auto_20160127_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creation',
            old_name='filer_path',
            new_name='file_path',
        ),
    ]
