# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0007_auto_20160204_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='image_size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creation',
            name='opacity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
