# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0008_auto_20160204_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='parent',
        ),
        migrations.AddField(
            model_name='creation',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_creation_parent_+', to='monthlyinterface.Creation'),
        ),
    ]
