# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0009_auto_20160309_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_creation_parent_+', to='monthlyinterface.Creation'),
        ),
    ]
