# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyinterface', '0010_auto_20160309_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='parent',
        ),
        migrations.AddField(
            model_name='creation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monthlyinterface.Creation'),
        ),
    ]
